---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"

testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.ad_auth
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"

galaxy:
  script:
    - ansible-galaxy role info buluma.ad_auth

role_testing_live:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.ad_auth
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
