---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: check adcli
      ansible.builtin.command: /usr/sbin/adcli --help
      changed_when: false

    - name: check realmd
      ansible.builtin.command: /usr/sbin/realm list
      changed_when: false

    - name: check samba common tools
      ansible.builtin.command: /usr/bin/net --version
      changed_when: false
